import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
type TaxExpense = { expense_category: string; total_cents: number; tax_deductible: boolean; form_1099_required: boolean; status: string };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);

export default async function TaxReportPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const params = await searchParams; const year = String(new Date().getFullYear()); const from = /^\d{4}-\d{2}-\d{2}$/.test(params.from || "") ? String(params.from) : `${year}-01-01`; const to = /^\d{4}-\d{2}-\d{2}$/.test(params.to || "") ? String(params.to) : `${year}-12-31`;
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login?next=/admin/expenses/tax-report"); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role === "artist") redirect("/admin");
  const { data } = await supabase.from("expenses").select("expense_category,total_cents,tax_deductible,form_1099_required,status").gte("expense_date", from).lte("expense_date", to).returns<TaxExpense[]>(); const expenses = data ?? []; const deductible = expenses.filter((item) => item.tax_deductible && item.status !== "rejected").reduce((sum, item) => sum + item.total_cents, 0); const nonDeductible = expenses.filter((item) => !item.tax_deductible).reduce((sum, item) => sum + item.total_cents, 0); const vendor1099 = expenses.filter((item) => item.form_1099_required).length;
  const byCategory = new Map<string, number>(); for (const item of expenses.filter((entry) => entry.tax_deductible && entry.status !== "rejected")) byCategory.set(item.expense_category, (byCategory.get(item.expense_category) ?? 0) + item.total_cents);
  const query = new URLSearchParams({ from, to }).toString();
  return <main className="min-h-screen bg-void px-5 py-8 text-bone sm:px-8"><div className="mx-auto max-w-5xl"><Link className="font-mono text-[10px] uppercase tracking-[.16em] text-ghost hover:text-flux" href="/admin/expenses">← Expense ledger</Link><header className="mt-5 flex flex-wrap items-end justify-between gap-5 border-b border-mercury pb-6"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-plasma">Treasury / tax readiness</p><h1 className="mt-3 font-display text-5xl leading-none">The clean paper trail.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-ghost">Operational summary only—not tax advice. Export the detailed CSV for your accountant.</p></div><a className="border border-flux px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-flux" href={`/api/expenses/tax-report?${query}`}>Download CSV</a></header><form className="mt-5 flex flex-wrap items-end gap-3 border border-mercury bg-carbon p-4"><label className="grid gap-1 font-mono text-[9px] uppercase tracking-[.1em] text-ghost">From<input className="border border-steel bg-void p-2 text-sm text-bone" defaultValue={from} name="from" type="date" /></label><label className="grid gap-1 font-mono text-[9px] uppercase tracking-[.1em] text-ghost">To<input className="border border-steel bg-void p-2 text-sm text-bone" defaultValue={to} name="to" type="date" /></label><button className="border border-steel px-4 py-2 font-mono text-[9px] uppercase text-ghost" type="submit">Update</button></form><section className="mt-5 grid gap-px border border-mercury bg-mercury sm:grid-cols-3"><Metric label="Deductible expenses" value={money(deductible)} /><Metric label="Non-deductible" value={money(nonDeductible)} /><Metric label="1099 review items" value={String(vendor1099)} /></section><section className="mt-5 border border-mercury bg-carbon"><header className="border-b border-mercury p-5"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-plasma">Deductible spend by category</p></header>{byCategory.size ? <div className="divide-y divide-steel">{[...byCategory.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([category, cents]) => <div className="flex items-center justify-between gap-4 p-5" key={category}><p className="text-sm capitalize">{category.replaceAll("_", " ")}</p><p className="font-mono text-sm text-flux">{money(cents)}</p></div>)}</div> : <p className="p-6 text-sm text-ghost">No deductible expenses in this date range.</p>}</section></div></main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article className="bg-carbon p-5"><p className="font-mono text-[9px] uppercase tracking-[.12em] text-ghost">{label}</p><p className="mt-3 font-display text-3xl leading-none text-flux">{value}</p></article>; }
