import Link from "next/link";
import { redirect } from "next/navigation";
import { ContactWarmthMeter } from "@/components/admin/ContactWarmthMeter";
import { FieldFilters } from "@/components/admin/FieldFilters";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
type Contact = { id: string; name: string; company: string | null; category: string; email: string | null; location: string | null; region: string | null; genre_focus: string[]; warmth_score: number; last_contact_date: string | null; next_outreach: string | null; disco_link: string | null };
const regions = [{ label: "Desert", value: "desert" }, { label: "Los Angeles", value: "los_angeles" }, { label: "San Diego", value: "san_diego" }] as const;
const categories = [{ label: "Bookers", value: "booker" }, { label: "Sync", value: "sync_agent" }, { label: "Managers", value: "manager" }, { label: "Promoters", value: "promoter" }] as const;
const dateLabel = (date: string | null) => date ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(`${date}T00:00:00`)) : "Not yet";

export default async function ContactsPage({ searchParams }: { searchParams: Promise<{ region?: string; category?: string }> }) {
  const { region, category } = await searchParams; const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login?next=/admin/contacts"); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role === "artist") redirect("/admin");
  let query = supabase.from("contacts").select("id,name,company,category,email,location,region,genre_focus,warmth_score,last_contact_date,next_outreach,disco_link").order("warmth_score", { ascending: false }); if (region) query = query.eq("region", region); if (category) query = query.eq("category", category); const { data } = await query.returns<Contact[]>(); const contacts = data ?? [];
  return <main className="min-h-screen bg-void px-5 py-8 text-bone sm:px-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-mercury pb-6"><div><Link className="font-mono text-[10px] uppercase tracking-[.16em] text-ghost hover:text-flux" href="/admin">← Operations</Link><p className="mt-5 font-mono text-[10px] uppercase tracking-[.18em] text-plasma">ØDIN Network / industry Rolodex</p><h1 className="mt-3 font-display text-5xl leading-none">Relationships, held close.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-ghost">Every connection, its context, and the next move—kept in one private field.</p></div><a className="border border-flux px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-flux" href="mailto:booking@odin.management?subject=New%20Odin%20Network%20contact">+ Add contact</a></header><div className="mt-5 grid gap-3"><FieldFilters active={region} label="Market" options={[...regions]} param="region" values={{ region, category }} /><FieldFilters active={category} label="Role" options={[...categories]} param="category" values={{ region, category }} /></div><section className="mt-5 grid gap-3">{contacts.length ? contacts.map((contact) => <article className="grid gap-5 border border-mercury bg-carbon p-5 transition hover:border-plasma sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center" key={contact.id}><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-display text-3xl leading-none">{contact.name}</h2><span className="border border-steel px-2 py-1 font-mono text-[9px] uppercase tracking-[.12em] text-ghost">{contact.category.replaceAll("_", " ")}</span></div><p className="mt-2 text-sm text-ghost">{contact.company || "Independent"} · {contact.location || contact.region?.replaceAll("_", " ") || "Location pending"}</p><p className="mt-3 text-xs text-ghost">{contact.genre_focus.length ? contact.genre_focus.join(" · ") : "Genre focus pending"}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 font-mono text-[10px] uppercase tracking-[.1em] text-ghost"><span>Last {dateLabel(contact.last_contact_date)}</span><span>Next {dateLabel(contact.next_outreach)}</span>{contact.email ? <a className="text-flux" href={`mailto:${contact.email}`}>Email ↗</a> : null}{contact.category === "sync_agent" && contact.disco_link ? <a className="text-flux" href={contact.disco_link} rel="noreferrer" target="_blank">Disco ↗</a> : null}</div></div><ContactWarmthMeter score={contact.warmth_score} /></article>) : <section className="border border-dashed border-steel bg-carbon p-8 text-sm text-ghost">No matching relationships in the field.</section>}</section></div></main>;
}
