import { LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { ArtistProfileForm } from "@/components/artist/ArtistProfileForm";
import { NoArtistState, PortalPageHeader, PortalStatus } from "@/components/artist/PortalPrimitives";
import { getArtistPortalContext } from "@/lib/artist-portal";

export const dynamic = "force-dynamic";

export default async function ArtistSettingsPage({ searchParams }: { searchParams: Promise<{ artist?: string }> }) {
  const { artist: preferred } = await searchParams; const { artist, isOperations, profile, user } = await getArtistPortalContext(preferred);
  if (!artist) return <NoArtistState isOperations={isOperations} />;
  return <><PortalPageHeader eyebrow="ØDIN artist field / settings" title="Your access, held clearly." copy="Keep your profile and catalog link current in one protected place." detail={isOperations ? "Operations preview" : "Artist account"} /><main className="mx-auto grid max-w-6xl gap-4 px-5 py-5 sm:px-8 sm:py-7 xl:grid-cols-[1.1fr_.9fr]"><section className="border border-mercury bg-carbon p-5 sm:p-6"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-plasma">Profile & music links</p><h2 className="mt-2 font-display text-3xl leading-none">How the field sees you.</h2><ArtistProfileForm initialDiscoLink={artist.disco_link} initialName={profile?.full_name || artist.artist_name} profileId={user.id} /><div className="mt-6 grid gap-3 border-t border-steel pt-5 text-sm text-ghost"><p className="flex items-center gap-3"><Mail className="h-4 w-4 text-plasma" />{user.email || "Email not available"}</p><p className="flex items-center gap-3"><ShieldCheck className="h-4 w-4 text-flux" />Role / <span className="capitalize text-bone">{profile?.role || "artist"}</span></p></div></section><section className="border border-mercury bg-carbon p-5 sm:p-6"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-plasma">Access boundary</p><h2 className="mt-2 font-display text-3xl leading-none">Your private field.</h2><div className="mt-5 grid gap-3"><div className="border border-steel bg-void/45 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm text-bone">Artist record</p><PortalStatus tone="good">Linked</PortalStatus></div><p className="mt-2 text-xs leading-5 text-ghost">{artist.artist_name} · {artist.home_market.replaceAll("_", " ")}</p></div><div className="border border-steel bg-void/45 p-4"><div className="flex items-center gap-2 text-flux"><LockKeyhole className="h-4 w-4" /><p className="font-mono text-[9px] uppercase tracking-[.12em]">Role-aware records</p></div><p className="mt-3 text-xs leading-5 text-ghost">Your schedules, music, tools, and payouts stay private. ØDIN operations manages the team-wide field and deal terms.</p></div></div></section></main></>;
}
