import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { SessionNoteComposer } from "@/components/admin/SessionNoteComposer";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
type Session = { id: string; project_id: string; title: string | null; session_date: string; engineer_name: string; session_status: string; hours: number; cost_cents: number; notes: string | null };
type Note = { id: string; author_id: string | null; author_role: string; title: string | null; content: string; parent_note_id: string | null; is_important: boolean; requires_response: boolean; resolved_at: string | null; created_at: string };
type Profile = { id: string; full_name: string | null };

export default async function SessionPage({ params }: { params: Promise<{ sessionId: string }> }) {
  const { sessionId } = await params; const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/login?next=/admin/engineering/sessions/${sessionId}`);
  const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role === "artist") redirect("/admin");
  const { data: session } = await supabase.from("engineering_sessions").select("id, project_id, title, session_date, engineer_name, session_status, hours, cost_cents, notes").eq("id", sessionId).maybeSingle<Session>(); if (!session) notFound();
  const [{ data: notesData }, { data: profilesData }] = await Promise.all([supabase.from("session_notes").select("id, author_id, author_role, title, content, parent_note_id, is_important, requires_response, resolved_at, created_at").eq("session_id", session.id).is("deleted_at", null).order("created_at").returns<Note[]>(), supabase.from("profiles").select("id, full_name").returns<Profile[]>()]);
  const names = new Map((profilesData ?? []).map((person) => [person.id, person.full_name || "ØDIN collaborator"])); const notes = notesData ?? [];
  return <main className="min-h-screen bg-void px-5 py-8 text-bone sm:px-8"><div className="mx-auto max-w-5xl"><Link className="font-mono text-[10px] uppercase tracking-[.16em] text-ghost hover:text-flux" href="/admin/engineering">← Engineering field</Link><header className="mt-5 border border-mercury bg-carbon p-6"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-plasma">Engineering session / {session.session_status}</p><h1 className="mt-3 font-display text-4xl leading-none">{session.title || "Studio session"}</h1><p className="mt-4 text-sm text-ghost">{session.engineer_name} · {session.session_date} · {session.hours}h</p><p className="mt-4 max-w-2xl text-xs leading-5 text-ghost">{session.notes || "No session overview yet."}</p></header><section className="mt-4 border border-mercury bg-carbon p-5"><div className="flex items-end justify-between gap-4 border-b border-steel pb-5"><div><p className="font-mono text-[9px] uppercase tracking-[.16em] text-plasma">Session notes</p><h2 className="mt-2 font-display text-3xl leading-none">Direction stays with the work.</h2></div><p className="font-mono text-[9px] uppercase tracking-[.1em] text-ghost">{notes.length} notes</p></div><div className="mt-5 grid gap-3">{notes.map((note) => <article className={`border p-4 ${note.parent_note_id ? "ml-6 border-steel bg-void/50" : "border-mercury bg-void/70"}`} key={note.id}><div className="flex flex-wrap items-center gap-2 font-mono text-[9px] uppercase tracking-[.1em]"><span className="text-flux">{note.author_id ? names.get(note.author_id) : note.author_role}</span>{note.is_important ? <span className="text-halo">Important</span> : null}{note.requires_response && !note.resolved_at ? <span className="text-plasma">Response requested</span> : null}{note.resolved_at ? <span className="text-flux">Resolved</span> : null}</div>{note.title ? <h3 className="mt-3 text-sm text-bone">{note.title}</h3> : null}<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-ghost">{note.content}</p></article>)}</div><SessionNoteComposer sessionId={session.id} /></section></div></main>;
}
