import Link from "next/link";
import { BookingForm } from "@/components/BookingForm";
import { OdinProcess } from "@/components/OdinProcess";
import { PromotionCard } from "@/components/PromotionCard";
import { RosterCard } from "@/components/RosterCard";
import { SectionHeading } from "@/components/SectionHeading";
import { SwapNetwork } from "@/components/SwapNetwork";
import { artists, promotions, services } from "@/lib/site-data";

export default function HomePage() {
  return <main>
    <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">ø</span><span>ØDIN<br />Management</span></Link><nav aria-label="Primary navigation"><a href="#roster">Roster</a><a href="#exchange">Exchange</a><a href="#work">Work</a><a href="#approach">Approach</a><a href="#contact">Contact</a></nav><Link className="header-link" href="/login">Enter ØDIN <span aria-hidden="true">→</span></Link></header>

    <section className="hero"><div className="hero-backdrop" aria-hidden="true"><span className="light-beam light-beam--violet" /><span className="light-beam light-beam--amber" /><span className="light-beam light-beam--rose" /></div><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">Artist management & booking</p><h1>Make the work.<br /><em>Keep moving.</em></h1><p className="hero-intro">ØDIN Management builds the rooms, relationships, and long-range infrastructure behind independent artists with something real to say.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Bring us a room <span aria-hidden="true">→</span></a><a className="button button-quiet" href="#roster">Meet the roster</a></div></div><div className="hero-signal" aria-label="ØDIN Management live signal"><div className="signal-orbit signal-orbit-one" /><div className="signal-orbit signal-orbit-two" /><div className="signal-center"><span>OM</span><small>Independent<br />by design</small></div><p>Now playing<br /><strong>Band room / take 01</strong></p></div></div><div className="hero-footer"><span><i className="live-dot" />Live from the band room</span><span>Powered by Whole Body Records · Los Angeles · Morongo Valley</span></div></section>

    <section className="manifesto section-shell"><p className="manifesto-number">01</p><div><p className="eyebrow">A different kind of management</p><h2>We don&apos;t rent attention.<br /><em>We build a field.</em></h2></div><div className="manifesto-copy"><p>Odin exists for artists who intend to make a body of work—not merely pass through a release cycle. We manage the operational gravity: the outreach, terms, rooms, and follow-through that make creative momentum possible.</p><p>Technology can open a door. It cannot replace a relationship. Every meaningful conversation stays human.</p></div></section>

    <section id="exchange" className="exchange section-shell"><SectionHeading eyebrow="The Odin exchange" title={<>Don&apos;t just book a city.<br /><em>Trade a stage.</em></>}><p>Odin pairs artists across markets so every bill carries two audiences, two local advocates, and a reason for the next show to happen.</p></SectionHeading><div className="exchange-layout"><SwapNetwork /><div className="exchange-copy"><p className="eyebrow">The triangulation</p><h3>Joshua Tree ↔ Los Angeles ↔ San Diego</h3><p>We bring an Odin artist into a partner&apos;s home market, then make the reciprocal desert show possible. Both artists cross-promote. Both venues get a fuller room. The relationship stays in the network.</p><ol><li><span>01</span>Match a compatible bill.</li><li><span>02</span>Build the paired show offer.</li><li><span>03</span>Make the two-market promotion.</li></ol><a className="text-link" href="mailto:artists@odin.management?subject=Odin%20Exchange%20network">Join the exchange <span aria-hidden="true">→</span></a></div></div><p className="exchange-footnote">Odin is building this pilot network deliberately: no extractive routing, no empty promises, and no automated close.</p></section>

    <section id="roster" className="roster section-shell"><SectionHeading eyebrow="The roster" title={<>Artists with a <em>long view.</em></>}><p>Music, moving image, and fieldwork from artists building culture without giving away the center.</p></SectionHeading><div className="roster-grid">{artists.map((artist) => <RosterCard artist={artist} key={artist.name} />)}</div><div className="roster-note"><span className="live-dot" />Limited new artist conversations open through 2026. <a href="mailto:artists@odin.management">Introduce your work ↗</a></div></section>

    <section id="work" className="work section-shell"><SectionHeading eyebrow="Promotion studio" title={<>We make the signal<br /><em>look like itself.</em></>}><p>Launch worlds, show posters, press moments, and release systems made to carry an artist&apos;s actual character into the room.</p></SectionHeading><div className="promotion-grid">{promotions.map((promotion) => <PromotionCard key={promotion.artist} promotion={promotion} />)}</div><div className="work-footer"><p>Every campaign is built from the work outward—never a borrowed template with a new name placed on top.</p><a className="text-link" href="mailto:artists@odin.management?subject=Promotion%20studio%20inquiry">See if we&apos;re a fit <span aria-hidden="true">→</span></a></div></section>

    <section className="showcase"><div className="showcase-label"><p className="eyebrow">Next signal</p><p>26 Sep 2026</p></div><div><p className="eyebrow">Red Dog Saloon · Showcase</p><h2>Bring the record<br />into the <em>room.</em></h2></div><a className="text-link light" href="mailto:booking@odin.management?subject=Red%20Dog%20Saloon%20Showcase">Request details <span aria-hidden="true">↗</span></a></section>

    <section id="approach" className="approach section-shell"><SectionHeading eyebrow="The Odin method" title={<>Tools should serve the <em>relationship.</em></>}><p>We pair thoughtful outreach systems with people who know how to listen, negotiate, and follow through.</p></SectionHeading><div className="approach-layout"><OdinProcess /><div className="operations-card"><p className="eyebrow">The management desk</p><div className="operations-line"><span>Venue intelligence</span><b>Active</b></div><div className="operations-line"><span>Artist press materials</span><b>Ready</b></div><div className="operations-line"><span>Outreach review</span><b>Human-led</b></div><div className="operations-line"><span>Contract & settlement</span><b>Protected</b></div><p className="operations-footer">Odin&apos;s private operating system is intentionally not public. Qualified partners receive the right level of access, at the right time.</p></div></div></section>

    <section className="services section-shell"><SectionHeading eyebrow="What we hold" title={<>The work around<br />the <em>work.</em></>} /><div className="service-list">{services.map(([number, name, copy]) => <article key={number}><span>{number}</span><h3>{name}</h3><p>{copy}</p></article>)}</div></section>

    <section id="contact" className="contact"><div className="contact-copy"><p className="eyebrow">Booking & management</p><h2>Let&apos;s make a<br /><em>true room.</em></h2><p>Bring us a date, a city, a strange idea, or the first thread of a longer conversation. We&apos;ll tell you plainly if there&apos;s a fit.</p><a className="text-link" href="mailto:booking@odin.management">booking@odin.management <span aria-hidden="true">↗</span></a><p className="contact-meta">ØDIN Management<br />Powered by Whole Body Records<br />(952) 212-1170</p></div><BookingForm /></section>

    <footer className="site-footer"><Link className="brand" href="/"><span className="brand-mark">Ã</span><span>Odin<br />Management</span></Link><div><p>Independent management infrastructure for independent artists.</p><p className="footer-fine">© 2026 ØDIN Management · Powered by Whole Body Records</p></div><div className="footer-links"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><a href="mailto:booking@odin.management">Email</a></div></footer>
  </main>;
}
