import { redirect } from "next/navigation";
import { TreasuryQuincunx } from "@/components/admin/TreasuryQuincunx";
import { formatUsd, summarizeRevenue, type StudioArm } from "@/lib/treasury/feed-first";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
type Revenue = { project_id: string | null; arm: StudioArm; amount_cents: number; revenue_type: string };
type Project = { id: string; project_code: string; title: string; investment_cents: number; status: string };
type Payout = { amount_cents: number };
const monthStart = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`; };

export default async function TreasuryPage() {
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login?next=/admin/treasury"); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); const isAdmin = profile?.role === "super_admin"; const isDirector = profile?.role === "booking_director"; if (!isAdmin && !isDirector) redirect("/admin/dashboard");
  const [{ data: monthRows }, { data: allRows }, { data: projects }, { data: pendingPayouts }] = await Promise.all([supabase.from("revenue_ledger").select("project_id,arm,amount_cents,revenue_type").gte("received_on", monthStart()).returns<Revenue[]>(), supabase.from("revenue_ledger").select("project_id,arm,amount_cents,revenue_type").returns<Revenue[]>(), supabase.from("projects").select("id,project_code,title,investment_cents,status").order("created_at", { ascending: false }).returns<Project[]>(), supabase.from("payouts").select("amount_cents").eq("status", "pending").returns<Payout[]>()]);
  const thisMonth = summarizeRevenue((monthRows ?? []).filter((row) => row.revenue_type !== "expense").map((row) => ({ arm: row.arm, amountCents: row.amount_cents }))); const allRevenue = (allRows ?? []).filter((row) => row.revenue_type !== "expense"); const payoutTotal = (pendingPayouts ?? []).reduce((sum, payout) => sum + payout.amount_cents, 0);
  const projectSummary = (projects ?? []).map((project) => { const revenue = allRevenue.filter((row) => row.project_id === project.id).reduce((sum, row) => sum + row.amount_cents, 0); return { ...project, revenue, net: revenue - project.investment_cents }; });
  return <main className="min-h-screen bg-void px-5 py-8 text-bone sm:px-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-mercury pb-6"><div><a className="font-mono text-[10px] uppercase tracking-[.16em] text-ghost hover:text-flux" href="/admin/money">← Money</a><p className="mt-5 font-mono text-[10px] uppercase tracking-[.18em] text-plasma">Whole Body Studios / central treasury</p><h1 className="mt-3 font-display text-5xl leading-none">The center holds the value.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-ghost">A real-time view of revenue across the four arms. Artist payouts remain visible before the system grows.</p></div><span className="border border-flux px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-flux">{isAdmin ? "Super-admin field" : "Director summary"}</span></header>{isDirector ? <p className="mt-5 border border-plasma/50 bg-plasma/5 p-4 text-xs leading-5 text-ghost">Director view shows operating summaries only. Expense lines, tax reports, and financial mutations remain reserved for the super-admin role.</p> : null}<div className="mt-6"><TreasuryQuincunx byArm={thisMonth.byArm} totalCents={thisMonth.totalCents} /></div><section className="mt-4 grid gap-px border border-mercury bg-mercury sm:grid-cols-4"><Metric label="Artist share · 50%" value={formatUsd(thisMonth.allocation.artist)} /><Metric label="Guild share · 25%" value={formatUsd(thisMonth.allocation.guild)} /><Metric label="Infrastructure · 15%" value={formatUsd(thisMonth.allocation.infrastructure)} /><Metric label="Pending payouts" value={formatUsd(payoutTotal)} /></section>{isAdmin ? <section className="mt-6 border border-mercury bg-carbon"><header className="border-b border-mercury p-5"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-plasma">Project profitability</p><h2 className="mt-2 font-display text-3xl leading-none">Every project carries its own story.</h2></header>{projectSummary.length ? <div className="divide-y divide-mercury">{projectSummary.map((project) => <article className="grid gap-3 p-5 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center" key={project.id}><div><p className="font-mono text-[9px] uppercase tracking-[.1em] text-ghost">{project.project_code} · {project.status.replaceAll("_", " ")}</p><h3 className="mt-2 font-display text-2xl leading-none">{project.title}</h3></div><Value label="Revenue" value={formatUsd(project.revenue)} /><Value label="Net" value={formatUsd(project.net)} /></article>)}</div> : <p className="p-6 text-sm text-ghost">No project ledger entries yet.</p>}</section> : null}</div></main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="bg-carbon p-5"><p className="font-mono text-[9px] uppercase tracking-[.12em] text-ghost">{label}</p><p className="mt-3 font-display text-3xl leading-none text-flux">{value}</p></article>; }
function Value({ label, value }: { label: string; value: string }) { return <div className="sm:text-right"><p className="font-mono text-[9px] uppercase tracking-[.1em] text-ghost">{label}</p><p className="mt-2 font-display text-2xl leading-none">{value}</p></div>; }
